import { ExplainAssistantError } from './contracts.js';
import { listWorkspace, readWorkspaceText, saveWorkspaceImageSnapshot, searchWorkspace, truncateValue } from './evidence.js';
export type ToolName = 'explain_read_session'|'explain_search_session'|'explain_read_workspace_file'|'explain_list_workspace'|'explain_search_workspace'|'explain_read_workspace_image'|'explain_get_model_context';
export interface ToolError { ok:false; code:string; message:string; retryable:boolean; details?:Record<string,unknown>; }
export interface ToolSuccess<T=unknown> { ok:true; value:T; truncated?:boolean; availableBytes?:number; sentBytes?:number; }
export type ToolResult<T=unknown> = ToolSuccess<T>|ToolError;
export interface ToolContext { sessionId:string; workspace?:string; imageSnapshotRoot?:string; signal?:AbortSignal; sessionQuery?:any; attachmentStore?:any; modelContext?:unknown; limits?:Partial<ToolLimits>; }
export interface ToolCall { name:string; arguments?:unknown; callId?:string; }
export interface ToolLimits { maxRounds:number; maxCalls:number; maxTotalResultBytes:number; maxSingleResultBytes:number; toolTimeoutMs:number; totalTimeoutMs:number; }
export const DEFAULT_TOOL_LIMITS:ToolLimits={maxRounds:8,maxCalls:32,maxTotalResultBytes:1024*1024,maxSingleResultBytes:128*1024,toolTimeoutMs:15_000,totalTimeoutMs:120_000};
export const TOOL_NAMES:readonly ToolName[]=['explain_read_session','explain_search_session','explain_read_workspace_file','explain_list_workspace','explain_search_workspace','explain_read_workspace_image','explain_get_model_context'];
const TOOL_ARGUMENTS:Record<ToolName,{properties:Record<string,unknown>;required?:readonly string[]}>= {
 explain_read_session:{properties:{seq:{type:'integer',minimum:0},before:{type:'integer',minimum:0,maximum:20},after:{type:'integer',minimum:0,maximum:20}},required:['seq']},
 explain_search_session:{properties:{query:{type:'string',minLength:1,maxLength:512},limit:{type:'integer',minimum:1,maximum:50}},required:['query']},
 explain_read_workspace_file:{properties:{path:{type:'string',minLength:1,maxLength:4096},offset:{type:'integer',minimum:0},length:{type:'integer',minimum:0}},required:['path']},
 explain_list_workspace:{properties:{path:{type:'string',minLength:1,maxLength:4096}}},
 explain_search_workspace:{properties:{query:{type:'string',minLength:1,maxLength:512},path:{type:'string',minLength:1,maxLength:4096}},required:['query']},
 explain_read_workspace_image:{properties:{path:{type:'string',minLength:1,maxLength:4096}},required:['path']},
 explain_get_model_context:{properties:{}}
};
export const TOOL_SCHEMAS=TOOL_NAMES.map(name=>({name,description:'Read-only explanation tool; never executes or mutates the main agent.',parameters:{type:'object',properties:TOOL_ARGUMENTS[name].properties,required:TOOL_ARGUMENTS[name].required,additionalProperties:false}}));
function bad(code:string,message:string,retryable=false,details?:Record<string,unknown>):ToolError{return{ok:false,code,message,retryable,details};}
function isToolError(v:unknown):v is ToolError{return !!v&&typeof v==='object'&&(v as any).ok===false&&typeof (v as any).code==='string';}
function objectArgs(v:unknown):Record<string,unknown>|ToolError{if(!v||typeof v!=='object'||Array.isArray(v))return bad('TOOL_INVALID_ARGUMENTS','工具参数必须是一个对象。');const r=v as Record<string,unknown>;return r.ok===true?bad('TOOL_INVALID_ARGUMENTS','工具参数不能自己声明成功结果。'):r;}
function only(a:Record<string,unknown>,keys:readonly string[]):ToolError|undefined{const allowed=new Set(keys);const unknown=Object.keys(a).filter(k=>!allowed.has(k));return unknown.length?bad('TOOL_INVALID_ARGUMENTS','存在工具不认识的参数。',false,{fields:unknown}):undefined;}
function str(a:Record<string,unknown>,key:string,max=4096,required=true):string|undefined|ToolError{const v=a[key];if(v===undefined&&!required)return undefined;if(typeof v!=='string'||(required&&!v)||v.length>max)return bad('TOOL_INVALID_ARGUMENTS','参数 '+key+' 无效。');return v;}
function uint(a:Record<string,unknown>,key:string,max=1_000_000,required=false):number|undefined|ToolError{const v=a[key];if(v===undefined&&!required)return undefined;if(!Number.isSafeInteger(v)||Number(v)<0||Number(v)>max)return bad('TOOL_INVALID_ARGUMENTS','参数 '+key+' 无效。');return Number(v);}
function mapError(e:unknown):ToolError{if(e instanceof ExplainAssistantError)return bad(e.code,e.message,e.retryable,e.details);
 // evidence.ts 抛的是 new Error('WORKSPACE_PATH_INVALID')——错误码在 **message** 里而不是 .code 上。
 // 旧实现只读 (e as any).code，于是所有路径类错误都匹配不上，一律降级成 TOOL_FAILED，
 // 界面既拿不到「路径越界」这个准确原因，也分不清是拒绝还是故障。
 const raw=(e as any)?.code;const c=typeof raw==='string'&&raw?raw:(e instanceof Error?e.message:undefined);
 if(c==='SESSION_ARCHIVED'||c==='ARCHIVED')return bad('SESSION_ARCHIVED','主对话已归档，不能再读取。');
 if(c==='WORKSPACE_PATH_INVALID')return bad('PATH_INVALID','工作区路径无效。');
 if(c==='WORKSPACE_PATH_ESCAPE')return bad('PATH_OUTSIDE_WORKSPACE','这个路径在小助手可读范围之外，已拒绝读取。');
 if(c==='WORKSPACE_NOT_FILE')return bad('PATH_INVALID','这个路径不是一个文件。');
 if(c==='IMAGE_TOO_LARGE')return bad('IMAGE_UNSUPPORTED','这张图片太大，超过了可读取的上限。');
 if(c==='IMAGE_CHANGED_DURING_READ')return bad('TOOL_FAILED','读取期间这张图片被改动过，结果不可信，请重试。',true);
 if(c==='SEARCH_QUERY_INVALID')return bad('TOOL_INVALID_ARGUMENTS','搜索关键词无效。');
 if(c==='ABORT_ERR'||(e as any)?.name==='AbortError')return bad('TOOL_TIMEOUT','工具已取消或超时。',true);
 // 未枚举的底层错误（Node 原生 ENOENT/EACCES/EISDIR 等）**不能把原始 message 直接当用户文案**：
 // 它是英文的，会原样进界面（§11.9 要求给非程序员看中文）。
 // 这里按常见 errno 给中文，原始信息放进 details 供排查，界面只显示中文原因。
 const errno=(e as any)?.code;
 if(errno==='ENOENT')return bad('TOOL_FAILED','找不到这个文件或目录，可能已被删除或名字写错了。',true,{cause:String((e as any)?.message??'')});
 if(errno==='EACCES'||errno==='EPERM')return bad('TOOL_FAILED','没有权限读取这个路径。',true,{cause:String((e as any)?.message??'')});
 if(errno==='EISDIR')return bad('TOOL_FAILED','这是一个目录，不是文件。',true,{cause:String((e as any)?.message??'')});
 if(errno==='ENOTDIR')return bad('TOOL_FAILED','路径中有一段不是目录。',true,{cause:String((e as any)?.message??'')});
 if(errno==='EMFILE'||errno==='ENFILE')return bad('TOOL_FAILED','系统打开的文件太多，请稍后重试。',true,{cause:String((e as any)?.message??'')});
 return bad('TOOL_FAILED','工具执行失败，没能完成这次读取。',true,{cause:String((e instanceof Error?e.message:String(e))??'')});}
function withTimeout<T>(work:(s:AbortSignal)=>Promise<T>,parent:AbortSignal|undefined,ms:number):Promise<T>{const c=new AbortController();const timer=setTimeout(()=>c.abort(),ms);const abort=()=>c.abort();if(parent?.aborted)c.abort();parent?.addEventListener('abort',abort,{once:true});return work(c.signal).finally(()=>{clearTimeout(timer);parent?.removeEventListener('abort',abort);});}
async function runSession(ctx:ToolContext,args:Record<string,unknown>,search:boolean):Promise<ToolResult>{if(!ctx.sessionQuery)return bad('SESSION_QUERY_UNAVAILABLE','主对话读取服务不可用。');const unknown=only(args,search?['query','limit']:['seq','before','after']);if(unknown)return unknown;try{if(search){const q=str(args,'query',512);if(typeof q!=='string')return bad('TOOL_INVALID_ARGUMENTS','查询内容无效。');const lv=uint(args,'limit',50);if(isToolError(lv))return lv;// C4：字段名必须是 limit。DSH 的 SessionEventSearchRequest 只有 limit，
// 传 pageSize 不会报错——引擎直接忽略，用户设的条数静默失效、回落默认 20。
// 取消信号是 searchEvents 的**第二个**参数（exec），不是塞进请求体。
const result=await ctx.sessionQuery.searchEvents({sessionId:ctx.sessionId,query:q,limit:lv??20},{signal:ctx.signal??new AbortController().signal});const clip=truncateValue(result,{maxBytes:ctx.limits?.maxSingleResultBytes??DEFAULT_TOOL_LIMITS.maxSingleResultBytes});return{ok:true,value:clip.value,truncated:clip.truncated,availableBytes:clip.bytes,sentBytes:clip.truncated?(ctx.limits?.maxSingleResultBytes??DEFAULT_TOOL_LIMITS.maxSingleResultBytes):clip.bytes};}const seq=uint(args,'seq',Number.MAX_SAFE_INTEGER,true);if(isToolError(seq)||typeof seq!=='number')return bad('TOOL_INVALID_ARGUMENTS','序号无效。');const bv=uint(args,'before',20);if(isToolError(bv))return bv;const av=uint(args,'after',20);if(isToolError(av))return av;const result=await ctx.sessionQuery.readEvent({sessionId:ctx.sessionId,seq,before:bv??0,after:av??0},ctx.signal);const clip=truncateValue(result,{maxBytes:ctx.limits?.maxSingleResultBytes??DEFAULT_TOOL_LIMITS.maxSingleResultBytes});return{ok:true,value:clip.value,truncated:clip.truncated,availableBytes:clip.bytes,sentBytes:clip.truncated?(ctx.limits?.maxSingleResultBytes??DEFAULT_TOOL_LIMITS.maxSingleResultBytes):clip.bytes};}catch(e){return mapError(e);}}
export async function executeTool(ctx:ToolContext,call:ToolCall):Promise<ToolResult>{if(!TOOL_NAMES.includes(call.name as ToolName))return bad('TOOL_NOT_ALLOWED','未知的只读工具：'+call.name);const parsed=objectArgs(call.arguments??{});if(isToolError(parsed))return parsed;const args=parsed;try{switch(call.name as ToolName){case'explain_read_session':return runSession(ctx,args,false);case'explain_search_session':return runSession(ctx,args,true);case'explain_read_workspace_file':{const u=only(args,['path','offset','length']);if(u)return u;if(!ctx.workspace)return bad('FILESYSTEM_UNAVAILABLE','工作区读取服务不可用。');const p=str(args,'path');if(isToolError(p)||typeof p!=='string')return bad('TOOL_INVALID_ARGUMENTS','路径无效。');const o=uint(args,'offset');if(isToolError(o))return o;const l=uint(args,'length');if(isToolError(l))return l;return{ok:true,value:await readWorkspaceText(ctx.workspace,p,{offset:o,length:l,signal:ctx.signal,sessionId:ctx.sessionId,limits:{maxBytes:ctx.limits?.maxSingleResultBytes??DEFAULT_TOOL_LIMITS.maxSingleResultBytes}})};}case'explain_list_workspace':{const u=only(args,['path']);if(u)return u;if(!ctx.workspace)return bad('FILESYSTEM_UNAVAILABLE','工作区读取服务不可用。');const p=args.path===undefined?'.':str(args,'path');if(isToolError(p)||typeof p!=='string')return bad('TOOL_INVALID_ARGUMENTS','路径无效。');return{ok:true,value:await listWorkspace(ctx.workspace,p,ctx.signal,ctx.sessionId)};}case'explain_search_workspace':{const u=only(args,['query','path']);if(u)return u;if(!ctx.workspace)return bad('FILESYSTEM_UNAVAILABLE','工作区读取服务不可用。');const q=str(args,'query',512);if(isToolError(q)||typeof q!=='string')return bad('TOOL_INVALID_ARGUMENTS','查询内容无效。');const p=args.path===undefined?'.':str(args,'path');if(isToolError(p)||typeof p!=='string')return bad('TOOL_INVALID_ARGUMENTS','路径无效。');return{ok:true,value:await searchWorkspace(ctx.workspace,q,p,ctx.signal,ctx.sessionId)};}case'explain_read_workspace_image':{const u=only(args,['path']);if(u)return u;if(!ctx.workspace||!ctx.imageSnapshotRoot)return bad('IMAGE_UNAVAILABLE','图片快照服务不可用。');const p=str(args,'path');if(isToolError(p)||typeof p!=='string')return bad('TOOL_INVALID_ARGUMENTS','路径无效。');return{ok:true,value:await saveWorkspaceImageSnapshot(ctx.workspace,p,{sessionId:ctx.sessionId,snapshotRoot:ctx.imageSnapshotRoot,signal:ctx.signal})};}case'explain_get_model_context':{const u=only(args,[]);return u??{ok:true,value:ctx.modelContext??{available:false}};}}}catch(e){return mapError(e);}}
export interface ToolLoopResult{calls:number;rounds:number;totalBytes:number;results:Array<{call:ToolCall;result:ToolResult}>;stopped?:ToolError;}
export async function executeToolLoop(ctx:ToolContext,calls:readonly ToolCall[],options:Partial<ToolLimits>={}):Promise<ToolLoopResult>{const limits={...DEFAULT_TOOL_LIMITS,...ctx.limits,...options};const started=Date.now();const results:ToolLoopResult['results']=[];let totalBytes=0;let rounds=0;for(const call of calls){rounds++;if(rounds>limits.maxRounds)return{calls:results.length,rounds,totalBytes,results,stopped:bad('LIMIT_EXCEEDED','工具调用轮数超过上限。')};if(results.length>=limits.maxCalls)return{calls:results.length,rounds,totalBytes,results,stopped:bad('LIMIT_EXCEEDED','工具调用次数超过上限。')};if(Date.now()-started>=limits.totalTimeoutMs)return{calls:results.length,rounds,totalBytes,results,stopped:bad('TOOL_TIMEOUT','工具总耗时超过上限。',true)};const result=await withTimeout(s=>executeTool({...ctx,signal:s,limits},call),ctx.signal,limits.toolTimeoutMs);totalBytes+=JSON.stringify(result).length;results.push({call,result});if(totalBytes>limits.maxTotalResultBytes)return{calls:results.length,rounds,totalBytes,results,stopped:bad('LIMIT_EXCEEDED','工具返回内容总量超过上限。')};}return{calls:results.length,rounds,totalBytes,results};}
